[broker]
rabbitmq-node  ansible_host=128.117.250.22  ansible_user=cc

[publishers]
publisher-node  ansible_host=128.117.250.23  ansible_user=cc

[subscribers]
subscriber-node  ansible_host=128.117.250.24  ansible_user=cc

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3

broker_private_ip=172.40.0.237
